export const examVersion = 'homlle-safety-0.4-exam-2';
const rows = [
 ['unknown','COSHH',true,'A customer offers an unlabelled cleaning liquid. What do you do?',['Smell it to identify it','Do not use it; obtain an approved labelled product','Try a small amount'],1,'Never identify an unknown chemical by smell or trial.'],
 ['mix','COSHH',true,'Can you mix familiar cleaning products?',['Yes, if diluted','Yes, for difficult stains','No; follow the approved product and method'],2,'Mixing can create dangerous reactions.'],
 ['sheet','COSHH',false,'What does a safety data sheet do?',['Replaces the job assessment','Informs the assessment of the actual task','Approves every use of the product'],1,'Assess the task, exposure and people as well as the product.'],
 ['ppe','PPE',true,'How should gloves and other PPE be selected?',['Any gloves are suitable','Choose by colour','Match the hazard, task and wearer using the assessment'],2,'No glove or mask protects against every substance.'],
 ['skin','PPE',false,'Your hands become red and itchy. What should you do?',['Ignore it until the next job','Stop exposure and report the concern promptly','Use stronger chemicals'],1,'Report symptoms early and review controls.'],
 ['avoid','Manual handling',true,'What comes before lifting technique?',['Avoid hazardous handling or reduce the risk first','Lift quickly','Ask the customer to help without planning'],0,'Training cannot make an unsafe task safe.'],
 ['weight','Manual handling',false,'Is one weight safe for everyone?',['Yes, under 25 kg','Yes, if two people lift','No; assess task, person, load and environment'],2,'There is no universal safe weight.'],
 ['trolley','Manual handling',true,'An ordinary trolley reaches stairs. What next?',['Drag it down slowly','Stop and arrange an assessed suitable method','Carry it fully loaded'],1,'The equipment and entire route must be suitable.'],
 ['turn','Manual handling',false,'How should you turn with a manageable load?',['Twist at the waist','Move your feet and keep the load close','Hold the load away from you'],1,'Use controlled movement and avoid twisting.'],
 ['pain','Manual handling',false,'A load shifts and you feel pain. What do you do?',['Push through it','Continue if the client is watching','Stop safely and report the problem'],2,'Pause and review the method rather than worsening an injury.'],
 ['danger','Safe visits',true,'Someone is in immediate danger. What takes priority?',['Wait for a routine manager reply','Call 999 and move to safety where possible','Finish the booking first'],1,'Do not delay emergency help for internal approval.'],
 ['contact','Safe visits',true,'No one can respond to your lone-worker check-ins. What do you do?',['Go anyway with a charged phone','Pause until a workable safety plan is arranged','Send an unattended message'],1,'A check-in needs an available responder and escalation plan.'],
 ['floor','Safe visits',false,'Is a warning sign enough for a wet slippery floor?',['Yes, always','Only if the sign is bright','No; prevent access until it is safe'],2,'Signs warn; they do not prevent access.'],
 ['secret','Safeguarding',true,'A customer discloses abuse and requests secrecy. What do you do?',['Promise secrecy','Investigate and confront the person','Listen, explain limits and follow the safeguarding route'],2,'Share necessary facts through appropriate secure channels.'],
 ['beauty','Safe visits',false,'Does passing this exam prove you can safely perform every cleaning task?',['No; task-specific practical training and assessment are still needed','Yes, every task','Yes, if the customer agrees'],0,'The videos and knowledge exam do not replace demonstration and observation of the actual task.'],
["lift","Manual handling",true,"Your equipment bag has been assessed as manageable. How should you lift it?",["Keep it away from you and jerk upwards","Take a stable position, secure the grip, keep it close and move smoothly","Keep your feet together and twist towards the door"],1,"For an assessed manageable load, plan the lift, use a stable stance and secure hold, bend comfortably at hips and knees, keep it close and avoid sudden movement."],
["split","Manual handling",false,"A full supply case blocks your view on narrow stairs. What is the best action?",["Carry it slowly without changing anything","Stop and plan smaller loads or another suitable assessed method","Ask the customer to guide you while you carry it blind"],1,"Change the task and check the whole route; carrying a load carefully does not remove an obstructed view or unsafe stairs."],
["team","Manual handling",false,"A second worker offers to help move equipment. What must happen first?",["Lift immediately because two people make it safe","Let each person choose when to lift","Assess the move together, agree signals and a safe place to set it down"],2,"Team handling needs planning for the load, route and both people; either person can stop."],
["sofa","Manual handling",true,"A customer asks you to move a heavy sofa outside the assessed cleaning scope. What do you do?",["Refuse the unsafe move, explain the limit and contact support for an assessed plan","Try it to protect your rating","Ask the customer to take one end without assessing it"],0,"Do not undertake unassessed heavy handling or move people outside your competence and approved scope."],
["repeat","Manual handling",false,"Repeated scrubbing and carrying are causing discomfort. What should you do?",["Ignore it because the items are light","Increase your speed to finish","Pause, report symptoms and review equipment and how the task is organised"],2,"Repetition and awkward reaching can cause strain even with light items. PPE does not remove these risks."],
["scope","Homlle job process",false,"The approved room checklist has not loaded. Should you accept the job?",["Yes, the map marker is enough","No; retry or refresh and review the exact scope before accepting","Yes, decide what to clean when you arrive"],1,"Review the approved room checklist, timing and pay before accepting on the dashboard."],
["arrival","Homlle job process",false,"You reach the correct property. What should you do before cleaning?",["Record I have arrived, check access and special notes, assess the area, then Start cleaning when safe","Mark every task complete","Start cleaning before checking the instructions"],0,"Arrival and Start cleaning are separate steps. Check customer instructions and safety before beginning."],
["task","Homlle job process",false,"A room cannot be accessed, so its task cannot be completed. What should you record?",["Completed, because it was not your fault","Nothing; leave the task unresolved","An honest Skipped or Issue reported status with a clear note, then save"],2,"Use More options or add note and Save detailed update. Do not mark unfinished work complete."],
["extra","Homlle job process",false,"A customer requests extra work needing more time or pay. What do you do?",["Use Add unexpected task to automatically increase the price","Report the issue for Homlle to review; do not treat it as agreed extra work","Do it without recording the change"],1,"Add unexpected task only covers work within remaining booked time and agreed pay, with recorded landlord approval."],
["evidence","Homlle job process",false,"An after photo is visible in the file preview. Is it saved to the booking?",["No; select Upload securely and check upload confirmation and the recorded photo list","Yes, selecting a file saves it","Yes, if the camera application closes"],0,"Select the evidence type and relevant task, upload it and check confirmation. Keep the photo relevant and private."]
];
const lessons={
 chemical:{title:'01 · COSHH and PPE',href:'/training-safety-v04/13-chemical-safety-transcript.txt',version:'0.4'},
 handling:{title:'02 · Manual handling',href:'/training-safety-v04/14-manual-handling-transcript.txt',version:'0.4'},
 visits:{title:'03 · Safe visits',href:'/training-safety-v04/15-safeguarding-transcript.txt',version:'0.4'},
 workflow:{title:'04 · Working with Homlle',href:'/training-working-guide-v01/index.html',version:'1.0-preview'}
};
const questions=rows.map(([id,category,critical,prompt,options,correct,feedback])=>({id,category,critical,prompt,options,correct,feedback,lesson:lessons[category==='Manual handling'?'handling':category==='COSHH'||category==='PPE'?'chemical':category==='Homlle job process'?'workflow':'visits']}));
export function publicSafetyExam(){return {version:examVersion,title:'Homlle job safety and working practices exam',passPercent:80,requiredCorrect:Math.ceil(questions.length*.8),estimatedMinutes:10,questions:questions.map(({correct,feedback,...q})=>q)};}
export function gradeSafetyExam(input){
 const bad=message=>Object.assign(new Error(message),{statusCode:422,code:'invalid-exam'});
 if(input?.version!==examVersion)throw bad('The exam has changed. Reload before trying again.');
 if(!/^[a-zA-Z0-9-]{16,64}$/.test(input.attemptId||''))throw bad('A valid attempt reference is required.');
 if(!input.answers||Array.isArray(input.answers)||Object.keys(input.answers).length!==questions.length)throw bad('Answer every question before submitting.');
 const answers={};let correctCount=0;const criticalMisses=[];const feedback=[];
 for(const q of questions){const answer=input.answers[q.id];if(!Number.isInteger(answer)||answer<0||answer>=q.options.length)throw bad('Choose one answer for every question.');answers[q.id]=answer;const correct=answer===q.correct;if(correct)correctCount++;else {if(q.critical)criticalMisses.push(q.id);feedback.push({question:q.prompt,explanation:q.feedback,lesson:q.lesson});}}
 const scorePercent=Math.round(correctCount/questions.length*100);
 return {attemptId:input.attemptId,version:examVersion,answers,correctCount,total:questions.length,scorePercent,passPercent:80,criticalMisses,passed:correctCount>=Math.ceil(questions.length*.8)&&criticalMisses.length===0,feedback,completedAt:new Date().toISOString(),assessmentType:'knowledge-only',practicalStatus:'not-assessed'};
}
